In [3]:
from pathlib import Path
import pandas as pd

data_path = Path("../data/heatwave_corpus_final.csv")

print("File found:", data_path.exists())
print("File location:", data_path.resolve())

corpus = pd.read_csv(
    data_path,
    encoding="utf-8-sig"
)

corpus_analysis = corpus[
    corpus["include_in_final_analysis"]
    .astype(str)
    .str.strip()
    .str.lower()
    .eq("true")
].copy()

print("Stored records:", len(corpus))
print("Included documents:", len(corpus_analysis))

File found: True
File location: C:\Users\mishu\Desktop\heatwave_project\data\heatwave_corpus_final.csv
Stored records: 80
Included documents: 72

In [4]:
##token analysis

import re

token_pattern = r"\b[\w]+(?:['’\-][\w]+)*\b"

tokens_unfiltered = (
    corpus_analysis[
        ["doc_id", "source_type", "publication_year", "clean_text"]
    ]
    .assign(
        token=lambda x:
        x["clean_text"].str.lower().str.findall(token_pattern)
    )
    .explode("token")
    .dropna(subset=["token"])
    .drop(columns="clean_text")
    .reset_index(drop=True)
)

print("Total tokens:", len(tokens_unfiltered))
print("Unique tokens:", tokens_unfiltered["token"].nunique())

Total tokens: 94940
Unique tokens: 7371

In [5]:
top_tokens = (
    tokens_unfiltered["token"]
    .value_counts()
    .head(40)
    .rename_axis("token")
    .reset_index(name="frequency")
)

top_tokens

           token  frequency
0            the       4250
1            and       3428
2             of       2672
3             to       2401
4             in       2094
5              a       1179
6           heat       1165
7            for        869
8            are        831
9             is        820
10        health        792
11      children        720
12          that        690
13            as        683
14          with        682
15       climate        671
16            on        637
17    bangladesh        575
18            by        514
19       extreme        487
20          from        464
21          this        413
22        change        412
23  temperatures        405
24            al        369
25            et        368
26          more        341
27            at        324
28            or        307
29          have        306
30         water        289
31           has        281
32         these        281
33        during        280
34           can        275
35         their        273
36             1        272
37      exposure        251
38      diseases        246
39            be        246

In [6]:
##removing stopwords

from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS

custom_stopwords = {"et", "al"}

tokens_filtered = tokens_unfiltered[
    ~tokens_unfiltered["token"].isin(ENGLISH_STOP_WORDS)
    & ~tokens_unfiltered["token"].isin(custom_stopwords)
    & tokens_unfiltered["token"].str.contains(r"[a-z]", regex=True)
].copy()

filtered_top_tokens = (
    tokens_filtered["token"]
    .value_counts()
    .head(40)
    .rename_axis("token")
    .reset_index(name="frequency")
)

print("Tokens before filtering:", len(tokens_unfiltered))
print("Tokens after filtering:", len(tokens_filtered))

filtered_top_tokens

Tokens before filtering: 94940
Tokens after filtering: 55557

           token  frequency
0           heat       1165
1         health        792
2       children        720
3        climate        671
4     bangladesh        575
5        extreme        487
6         change        412
7   temperatures        405
8          water        289
9       exposure        251
10      diseases        246
11       effects        242
12   temperature        241
13         study        216
14             c        203
15          days        201
16       impacts        201
17         urban        201
18     heatwaves        189
19         risks        184
20    vulnerable        182
21        stress        178
22         child        176
23          said        169
24    conditions        165
25          risk        161
26     household        161
27         areas        160
28      increase        159
29     education        154
30        people        151
31          high        151
32   significant        147
33  particularly        145
34          work        144
35      heatwave        144
36      climatic        142
37  heat-related        141
38        school        141
39          year        140

In [7]:
## TF-IDF
##

number_of_documents = corpus_analysis["doc_id"].nunique()

token_statistics = (
    tokens_filtered
    .groupby("token")
    .agg(
        frequency=("token", "size"),
        document_frequency=("doc_id", "nunique")
    )
    .reset_index()
)

token_statistics["document_percentage"] = (
    token_statistics["document_frequency"]
    / number_of_documents
    * 100
).round(1)

token_statistics = token_statistics.sort_values(
    ["document_frequency", "frequency"],
    ascending=False
).reset_index(drop=True)

token_statistics.head(40)

           token  frequency  document_frequency  document_percentage
0           heat       1165                  69                 95.8
1     bangladesh        575                  68                 94.4
2        climate        671                  67                 93.1
3       children        720                  65                 90.3
4         health        792                  64                 88.9
5   temperatures        405                  62                 86.1
6         change        412                  60                 83.3
7     vulnerable        182                  59                 81.9
8        extreme        487                  58                 80.6
9           risk        161                  54                 75.0
10          high        151                  51                 70.8
11         risks        184                  50                 69.4
12       country        132                  50                 69.4
13         water        289                  49                 68.1
14   temperature        241                  49                 68.1
15       impacts        201                  46                 63.9
16     heatwaves        189                  46                 63.9
17  particularly        145                  45                 62.5
18        people        151                  44                 61.1
19          year        140                  44                 61.1
20       weather        135                  44                 61.1
21        impact        120                  44                 61.1
22        stress        178                  43                 59.7
23     including        103                  43                 59.7
24     according         72                  43                 59.7
25          like        117                  42                 58.3
26    conditions        165                  41                 56.9
27  heat-related        141                  41                 56.9
28       million        111                  41                 56.9
29        severe         77                  41                 56.9
30           day         76                  41                 56.9
31     education        154                  40                 55.6
32    government         61                  40                 55.6
33          days        201                  39                 54.2
34          said        169                  39                 54.2
35      heatwave        144                  39                 54.2
36        rising        127                  39                 54.2
37          rise         90                  39                 54.2
38   dehydration         66                  38                 52.8
39         women        116                  37                 51.4

In [8]:
#further cleaning 

bangladesh_scope_exclusions = [
    "DOC_045",
    "DOC_050",
    "DOC_065",
    "DOC_066",
    "DOC_072",
    "DOC_076",
    "DOC_078"
]
##excluded because these articles are not related to Bangladesh

# Preserve the previous inclusion decision
previously_included = (
    corpus["include_in_clean_analysis"]
    .astype(str)
    .str.strip()
    .str.lower()
    .eq("true")
)

# Create the final inclusion variable
corpus["include_in_final_analysis"] = (
    previously_included
    & ~corpus["doc_id"].isin(bangladesh_scope_exclusions)
)

# Record exclusion reasons
corpus["final_exclusion_reason"] = ""

corpus.loc[
    ~previously_included,
    "final_exclusion_reason"
] = "Previously excluded as an exact duplicate"

corpus.loc[
    corpus["doc_id"].isin(bangladesh_scope_exclusions),
    "final_exclusion_reason"
] = (
    "Background source: discusses children and heat globally "
    "but has no substantive Bangladesh focus"
)

# Recreate the analytical corpus
corpus_analysis = corpus[
    corpus["include_in_final_analysis"]
].copy()

print("All stored records:", len(corpus))
print("Final included documents:", len(corpus_analysis))
print(corpus_analysis["source_type"].value_counts())

All stored records: 80
Final included documents: 72
source_type
news paper       46
civil society    16
scientific        9
others            1
Name: count, dtype: int64

In [9]:
corpus.to_csv(
    "../data/heatwave_corpus_final.csv",
    index=False,
    encoding="utf-8-sig"
)

In [10]:
##token analysis 2

import re

token_pattern = r"\b[\w]+(?:['’\-][\w]+)*\b"

tokens_unfiltered = (
    corpus_analysis[
        ["doc_id", "source_type", "publication_year", "clean_text"]
    ]
    .assign(
        token=lambda x:
        x["clean_text"].str.lower().str.findall(token_pattern)
    )
    .explode("token")
    .dropna(subset=["token"])
    .drop(columns="clean_text")
    .reset_index(drop=True)
)

print("Total tokens:", len(tokens_unfiltered))
print("Unique tokens:", tokens_unfiltered["token"].nunique())

##removing stopwords

from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS

custom_stopwords = {"et", "al"}

tokens_filtered = tokens_unfiltered[
    ~tokens_unfiltered["token"].isin(ENGLISH_STOP_WORDS)
    & ~tokens_unfiltered["token"].isin(custom_stopwords)
    & tokens_unfiltered["token"].str.contains(r"[a-z]", regex=True)
].copy()

filtered_top_tokens = (
    tokens_filtered["token"]
    .value_counts()
    .head(40)
    .rename_axis("token")
    .reset_index(name="frequency")
)

print("Tokens before filtering:", len(tokens_unfiltered))
print("Tokens after filtering:", len(tokens_filtered))

filtered_top_tokens

Total tokens: 94940
Unique tokens: 7371
Tokens before filtering: 94940
Tokens after filtering: 55557

           token  frequency
0           heat       1165
1         health        792
2       children        720
3        climate        671
4     bangladesh        575
5        extreme        487
6         change        412
7   temperatures        405
8          water        289
9       exposure        251
10      diseases        246
11       effects        242
12   temperature        241
13         study        216
14             c        203
15          days        201
16       impacts        201
17         urban        201
18     heatwaves        189
19         risks        184
20    vulnerable        182
21        stress        178
22         child        176
23          said        169
24    conditions        165
25          risk        161
26     household        161
27         areas        160
28      increase        159
29     education        154
30        people        151
31          high        151
32   significant        147
33  particularly        145
34          work        144
35      heatwave        144
36      climatic        142
37  heat-related        141
38        school        141
39          year        140

In [11]:
## TF-IDF 2
##

number_of_documents = corpus_analysis["doc_id"].nunique()

token_statistics = (
    tokens_filtered
    .groupby("token")
    .agg(
        frequency=("token", "size"),
        document_frequency=("doc_id", "nunique")
    )
    .reset_index()
)

token_statistics["document_percentage"] = (
    token_statistics["document_frequency"]
    / number_of_documents
    * 100
).round(1)

token_statistics = token_statistics.sort_values(
    ["document_frequency", "frequency"],
    ascending=False
).reset_index(drop=True)

token_statistics.head(40)

           token  frequency  document_frequency  document_percentage
0           heat       1165                  69                 95.8
1     bangladesh        575                  68                 94.4
2        climate        671                  67                 93.1
3       children        720                  65                 90.3
4         health        792                  64                 88.9
5   temperatures        405                  62                 86.1
6         change        412                  60                 83.3
7     vulnerable        182                  59                 81.9
8        extreme        487                  58                 80.6
9           risk        161                  54                 75.0
10          high        151                  51                 70.8
11         risks        184                  50                 69.4
12       country        132                  50                 69.4
13         water        289                  49                 68.1
14   temperature        241                  49                 68.1
15       impacts        201                  46                 63.9
16     heatwaves        189                  46                 63.9
17  particularly        145                  45                 62.5
18        people        151                  44                 61.1
19          year        140                  44                 61.1
20       weather        135                  44                 61.1
21        impact        120                  44                 61.1
22        stress        178                  43                 59.7
23     including        103                  43                 59.7
24     according         72                  43                 59.7
25          like        117                  42                 58.3
26    conditions        165                  41                 56.9
27  heat-related        141                  41                 56.9
28       million        111                  41                 56.9
29        severe         77                  41                 56.9
30           day         76                  41                 56.9
31     education        154                  40                 55.6
32    government         61                  40                 55.6
33          days        201                  39                 54.2
34          said        169                  39                 54.2
35      heatwave        144                  39                 54.2
36        rising        127                  39                 54.2
37          rise         90                  39                 54.2
38   dehydration         66                  38                 52.8
39         women        116                  37                 51.4

In [12]:
##Lemmatization

%pip install -q spacy

import sys
import subprocess
import spacy

try:
    nlp = spacy.load("en_core_web_sm")
except OSError:
    subprocess.check_call([
        sys.executable,
        "-m",
        "spacy",
        "download",
        "en_core_web_sm"
    ])
    nlp = spacy.load("en_core_web_sm")

# Keep the components required for accurate lemmatization
nlp.disable_pipes("parser", "ner")

Note: you may need to restart the kernel to use updated packages.

['parser', 'ner']

In [13]:
import sys

print("Python:", sys.executable)
print("spaCy version:", spacy.__version__)

!{sys.executable} -m spacy download en_core_web_sm

Python: C:\Users\mishu\anaconda3\python.exe
spaCy version: 3.8.16

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\mishu\anaconda3\Lib\site-packages\spacy\__main__.py", line 4, in <module>
    setup_cli()
    ~~~~~~~~~^^
  File "C:\Users\mishu\anaconda3\Lib\site-packages\spacy\cli\_util.py", line 77, in setup_cli
    command = get_command(app)
  File "C:\Users\mishu\anaconda3\Lib\site-packages\typer\main.py", line 350, in get_command
    click_command: click.Command = get_group(typer_instance)
                                   ~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\mishu\anaconda3\Lib\site-packages\typer\main.py", line 332, in get_group
    group = get_group_from_info(
        TyperInfo(typer_instance),
        pretty_exceptions_short=typer_instance.pretty_exceptions_short,
        rich_markup_mode=typer_instance.rich_markup_mode,
    )
  File "C:\Users\mishu\anaconda3\Lib\site-packages\typer\main.py", line 483, in get_group_from_info
    command = get_command_from_info(
        command_info=command_info,
        pretty_exceptions_short=pretty_exceptions_short,
        rich_markup_mode=rich_markup_mode,
    )
  File "C:\Users\mishu\anaconda3\Lib\site-packages\typer\main.py", line 577, in get_command_from_info
    ) = get_params_convertors_ctx_param_name_from_function(command_info.callback)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mishu\anaconda3\Lib\site-packages\typer\main.py", line 553, in get_params_convertors_ctx_param_name_from_function
    click_param, convertor = get_click_param(param)
                             ~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\mishu\anaconda3\Lib\site-packages\typer\main.py", line 877, in get_click_param
    TyperOption(
    ~~~~~~~~~~~^
        # Option
        ^^^^^^^^
    ...<29 lines>...
        rich_help_panel=parameter_info.rich_help_panel,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ),
    ^
  File "C:\Users\mishu\anaconda3\Lib\site-packages\typer\core.py", line 489, in __init__
    super().__init__(**kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\mishu\anaconda3\Lib\site-packages\click\core.py", line 3030, in __init__
    self._validate(prompt, deprecated)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mishu\anaconda3\Lib\site-packages\click\core.py", line 3163, in _validate
    raise TypeError("Secondary flag is not valid for non-boolean flag.")
TypeError: Secondary flag is not valid for non-boolean flag.

In [14]:
import importlib
import spacy
from spacy.cli.download import download

# Download the model without using spaCy's broken command-line interface
download("en_core_web_sm")

# Make the newly installed package visible
importlib.invalidate_caches()

# Load the model
nlp = spacy.load("en_core_web_sm")

# These components are unnecessary for lemmatization
nlp.disable_pipes("parser", "ner")

print("spaCy model loaded successfully.")

✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.
spaCy model loaded successfully.

In [15]:
import re
import pandas as pd
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS

custom_stopwords = {"et", "al"}

document_columns = [
    "doc_id",
    "source_type",
    "publication_year",
    "clean_text"
]

documents_for_lemmatization = corpus_analysis[
    document_columns
].copy()

documents_for_lemmatization["clean_text"] = (
    documents_for_lemmatization["clean_text"]
    .fillna("")
    .astype(str)
)

lemmatized_records = []

texts = documents_for_lemmatization["clean_text"].tolist()

for document_row, processed_document in zip(
    documents_for_lemmatization.itertuples(index=False),
    nlp.pipe(texts, batch_size=8)
):
    for word in processed_document:

        original_token = word.text.lower().strip()
        lemma = word.lemma_.lower().strip()

        # Remove spaces and punctuation
        if word.is_space or word.is_punct:
            continue

        # Remove standard and custom stopwords
        if original_token in ENGLISH_STOP_WORDS:
            continue

        if lemma in ENGLISH_STOP_WORDS:
            continue

        if original_token in custom_stopwords:
            continue

        if lemma in custom_stopwords:
            continue

        # Remove numbers and symbols without letters
        if not re.search(r"[a-z]", lemma):
            continue

        lemmatized_records.append({
            "doc_id": document_row.doc_id,
            "source_type": document_row.source_type,
            "publication_year": document_row.publication_year,
            "original_token": original_token,
            "lemma": lemma
        })

tokens_lemmatized = pd.DataFrame(lemmatized_records)

print("Included documents:",
      tokens_lemmatized["doc_id"].nunique())

print("Total lemmatized tokens:",
      len(tokens_lemmatized))

print("Unique original tokens:",
      tokens_lemmatized["original_token"].nunique())

print("Unique lemmas:",
      tokens_lemmatized["lemma"].nunique())

Included documents: 72
Total lemmatized tokens: 56408
Unique original tokens: 6382
Unique lemmas: 5002

In [16]:
lemma_examples = (
    tokens_lemmatized[
        tokens_lemmatized["original_token"]
        != tokens_lemmatized["lemma"]
    ][["original_token", "lemma"]]
    .drop_duplicates()
    .head(40)
)

lemma_examples

    original_token       lemma
2         exposing      expose
3         millions     million
4         children       child
12            aged         age
16    experiencing  experience
26       according      accord
29             led        lead
34       published     publish
41         tripled      triple
48          months       month
49            days         day
54      increasing    increase
66        findings     finding
69           wider        wide
82         exposed      expose
92         doubled      double
104       youngest       young
105         facing        face
106       greatest       great
110      estimates    estimate
129         higher        high
137         bodies        body
139         faster        fast
140         adults       adult
152       existing       exist
154     conditions   condition
156       learning       learn
160        focuses       focus
163       measured     measure
164          using         use
178       prevents     prevent
181        cooling        cool
184          faces        face
202      projected     project
225         driven       drive
236    projections  projection
238        growing        grow
240      preparing     prepare
248        periods      period
252       reducing      reduce

In [17]:
number_of_documents = corpus_analysis["doc_id"].nunique()

lemma_statistics = (
    tokens_lemmatized
    .groupby("lemma")
    .agg(
        frequency=("lemma", "size"),
        document_frequency=("doc_id", "nunique")
    )
    .reset_index()
)

lemma_statistics["document_percentage"] = (
    lemma_statistics["document_frequency"]
    / number_of_documents
    * 100
).round(1)

lemma_statistics = lemma_statistics.sort_values(
    ["document_frequency", "frequency"],
    ascending=False
).reset_index(drop=True)

print("Documents:", number_of_documents)
print("Total lemmatized tokens:", len(tokens_lemmatized))
print("Unique lemmas:", tokens_lemmatized["lemma"].nunique())

lemma_statistics.head(50)

Documents: 72
Total lemmatized tokens: 56408
Unique lemmas: 5002

           lemma  frequency  document_frequency  document_percentage
0           heat       1364                  69                 95.8
1    temperature        647                  69                 95.8
2     bangladesh        635                  69                 95.8
3        climate        777                  68                 94.4
4          child       1029                  67                 93.1
5         health        805                  64                 88.9
6         change        509                  63                 87.5
7           high        299                  62                 86.1
8        country        242                  61                 84.7
9            day        289                  60                 83.3
10    vulnerable        195                  60                 83.3
11       extreme        502                  59                 81.9
12          risk        355                  59                 81.9
13        impact        342                  58                 80.6
14      heatwave        334                  56                 77.8
15          rise        238                  54                 75.0
16      increase        463                  52                 72.2
17        relate        226                  51                 70.8
18         water        303                  49                 68.1
19       include        160                  49                 68.1
20            ’s        363                  48                 66.7
21          year        294                  48                 66.7
22    government         85                  48                 66.7
23        school        249                  47                 65.3
24  particularly        145                  45                 62.5
25       weather        137                  45                 62.5
26       million        135                  45                 62.5
27          need        119                  45                 62.5
28       illness        118                  45                 62.5
29          face        112                  45                 62.5
30        people        160                  44                 61.1
31           say        199                  43                 59.7
32        stress        190                  43                 59.7
33           hot        131                  43                 59.7
34          like        121                  43                 59.7
35        accord         72                  43                 59.7
36          area        201                  42                 58.3
37     condition        185                  42                 58.3
38         cause        139                  42                 58.3
39        affect        173                  41                 56.9
40    experience        138                  41                 56.9
41        severe         77                  41                 56.9
42     education        154                  40                 55.6
43          time        121                  40                 55.6
44         world        108                  40                 55.6
45       protect         95                  40                 55.6
46        family         88                  40                 55.6
47         woman        137                  39                 54.2
48          lead        118                  39                 54.2
49        action        108                  39                 54.2

In [18]:
from pathlib import Path

output_folder = Path("../outputs")
output_folder.mkdir(exist_ok=True)

tokens_lemmatized.to_csv(
    output_folder / "tokens_lemmatized.csv",
    index=False,
    encoding="utf-8-sig"
)

lemma_statistics.to_csv(
    output_folder / "lemma_statistics.csv",
    index=False,
    encoding="utf-8-sig"
)

In [19]:
short_lemma_review = (
    tokens_lemmatized[
        tokens_lemmatized["lemma"].str.len() <= 2
    ]
    .groupby(["lemma", "original_token"])
    .agg(
        frequency=("lemma", "size"),
        document_frequency=("doc_id", "nunique")
    )
    .reset_index()
    .sort_values(
        ["document_frequency", "frequency"],
        ascending=False
    )
    .reset_index(drop=True)
)

short_lemma_review.head(50)

   lemma original_token  frequency  document_frequency
0     ’s             ’s        363                  48
1     's             's        150                  32
2      c              c        199                  29
3     dr             dr         23                  10
4      f              f         11                   6
5     km             km         11                   4
6     el             el          9                   4
7      p              p         19                   3
8     ci             ci         24                   2
9      b              b         10                   2
10     z              z          8                   2
11    sk             sk          6                   2
12    wu             wu          6                   2
13    sd             sd          4                   2
14    c.             c.          3                   2
15    ii             ii          3                   2
16     r              r          3                   2
17     e              e          2                   2
18    la             la          2                   2
19    md             md          2                   2
20    mm             mm          2                   2
21    xu             xu          2                   2
22    ft             ft          7                   1
23    a4             a4          4                   1
24    ea            eas          4                   1
25    ac             ac          3                   1
26    ea             ea          3                   1
27    q.             q.          3                   1
28    a5             a5          2                   1
29    ia             ia          2                   1
30    kg             kg          2                   1
31    mr             mr          2                   1
32    wb             wb          2                   1
33     x              x          2                   1
34    2c             2c          1                   1
35    5c             5c          1                   1
36    a.             a.          1                   1
37    a1             a1          1                   1
38    a2             a2          1                   1
39    a3             a3          1                   1
40    a7             a7          1                   1
41    a8             a8          1                   1
42    a9             a9          1                   1
43    b.             b.          1                   1
44    bi             bi          1                   1
45    cm             cm          1                   1
46     d              d          1                   1
47    dg             dg          1                   1
48    em             em          1                   1
49    g.             g.          1                   1

In [20]:
lemma_text = tokens_lemmatized["lemma"].astype(str)

technical_noise_mask = (
    # Possessive fragments and titles
    lemma_text.isin({"’s", "'s", "dr"})
    
    # Any isolated letter
    | lemma_text.str.fullmatch(r"[a-z]", na=False)
    
    # Letter followed by a period, such as c. or q.
    | lemma_text.str.fullmatch(r"[a-z]\.", na=False)
    
    # Table labels such as a1, a4 or a9
    | lemma_text.str.fullmatch(r"[a-z]\d+", na=False)
    
    # Malformed fragments such as 2c or 5c
    | lemma_text.str.fullmatch(r"\d+[a-z]", na=False)
)

removed_technical_noise = (
    tokens_lemmatized.loc[technical_noise_mask, "lemma"]
    .value_counts()
    .rename_axis("removed_lemma")
    .reset_index(name="frequency")
)

tokens_base_clean = (
    tokens_lemmatized.loc[~technical_noise_mask]
    .copy()
    .reset_index(drop=True)
)

print("Tokens before:", len(tokens_lemmatized))
print("Tokens after:", len(tokens_base_clean))
print("Tokens removed:", technical_noise_mask.sum())

removed_technical_noise

Tokens before: 56408
Tokens after: 55538
Tokens removed: 870

   removed_lemma  frequency
0             ’s        363
1              c        199
2             's        150
3             dr         23
4              p         19
..           ...        ...
62            h7          1
63            h8          1
64            h9          1
65         1990s          1
66           10c          1

[67 rows x 2 columns]

In [21]:
tokens_base_clean.to_csv(
    "../outputs/tokens_base_clean.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Saved: ../outputs/tokens_base_clean.csv")

Saved: ../outputs/tokens_base_clean.csv

In [22]:
# Convert the lemma column to text
lemma_text = tokens_lemmatized["lemma"].astype(str)

# Identify clear technical noise
technical_noise_mask = (
    # Possessive fragments and titles
    lemma_text.isin({"’s", "'s", "dr"})
    
    # Isolated letters such as c, f, p and r
    | lemma_text.str.fullmatch(r"[a-z]", na=False)
    
    # Letter followed by a period, such as c. or q.
    | lemma_text.str.fullmatch(r"[a-z]\.", na=False)
    
    # Table labels such as a1, a4 and h7
    | lemma_text.str.fullmatch(r"[a-z]\d+", na=False)
    
    # Temperature fragments such as 2c, 10c and 95f
    | lemma_text.str.fullmatch(r"\d{1,3}[cf]", na=False)
)

# Create an audit table of removed lemmas
removed_technical_noise = (
    tokens_lemmatized.loc[
        technical_noise_mask,
        "lemma"
    ]
    .value_counts()
    .rename_axis("removed_lemma")
    .reset_index(name="frequency")
)

# Create the cleaned token table
tokens_base_clean = (
    tokens_lemmatized.loc[
        ~technical_noise_mask
    ]
    .copy()
    .reset_index(drop=True)
)

# Count decade expressions before cleaning
decades_before = (
    tokens_lemmatized.loc[
        tokens_lemmatized["lemma"].str.fullmatch(
            r"\d{4}s",
            na=False
        ),
        "lemma"
    ]
    .value_counts()
    .rename("frequency_before")
)

# Count decade expressions after cleaning
decades_after = (
    tokens_base_clean.loc[
        tokens_base_clean["lemma"].str.fullmatch(
            r"\d{4}s",
            na=False
        ),
        "lemma"
    ]
    .value_counts()
    .rename("frequency_after")
)

# Compare decade counts before and after cleaning
decade_validation = (
    pd.concat(
        [decades_before, decades_after],
        axis=1
    )
    .fillna(0)
    .astype(int)
    .reset_index()
    .rename(columns={"lemma": "decade"})
)

decade_validation["all_occurrences_retained"] = (
    decade_validation["frequency_before"]
    == decade_validation["frequency_after"]
)

# Display validation results
print("Tokens before:", len(tokens_lemmatized))
print("Tokens after:", len(tokens_base_clean))
print("Tokens removed:", technical_noise_mask.sum())

print("\nRemoved technical noise:")
display(removed_technical_noise)

print("\nDecade validation:")
display(decade_validation)

# Save the corrected token table
tokens_base_clean.to_csv(
    "../outputs/tokens_base_clean.csv",
    index=False,
    encoding="utf-8-sig"
)

print("\nSaved: ../outputs/tokens_base_clean.csv")

Tokens before: 56408
Tokens after: 55550
Tokens removed: 858

Removed technical noise:

   removed_lemma  frequency
0             ’s        363
1              c        199
2             's        150
3             dr         23
4              p         19
5              f         11
6              b         10
7              z          8
8            40c          6
9            42c          4
10          108f          4
11            a4          4
12             r          3
13            q.          3
14            c.          3
15           46c          2
16             e          2
17             x          2
18            a5          2
19           44c          1
20          111f          1
21           35c          1
22            a.          1
23            5c          1
24           45c          1
25             h          1
26            2c          1
27             d          1
28             s          1
29             y          1
30          104f          1
31           37c          1
32           38c          1
33            g.          1
34            a3          1
35            a2          1
36            a1          1
37            a8          1
38            a7          1
39            a9          1
40           a12          1
41             t          1
42             m          1
43           a14          1
44           a13          1
45           a15          1
46            b.          1
47             v          1
48             n          1
49            h1          1
50            h2          1
51            h3          1
52            h4          1
53            h5          1
54            h6          1
55            h7          1
56            h8          1
57            h9          1
58           10c          1

Decade validation:

  decade  frequency_before  frequency_after  all_occurrences_retained
0  1950s                 2                2                      True
1  1980s                 1                1                      True
2  1970s                 1                1                      True
3  1990s                 1                1                      True

Saved: ../outputs/tokens_base_clean.csv

In [23]:
thematic_stopwords = {
    "accord",        # produced from "according"
    "say",           # reporting verb: said, says
    "include",       # generic listing word
    "like",          # generic comparison word
    "particularly",  # generic emphasis word
    "relate"         # often produced from "heat-related"
}

tokens_thematic = (
    tokens_base_clean[
        ~tokens_base_clean["lemma"].isin(thematic_stopwords)
    ]
    .copy()
    .reset_index(drop=True)
)

removed_thematic_words = (
    tokens_base_clean[
        tokens_base_clean["lemma"].isin(thematic_stopwords)
    ]["lemma"]
    .value_counts()
    .rename_axis("removed_lemma")
    .reset_index(name="frequency")
)

print("Base-clean tokens:", len(tokens_base_clean))
print("Thematic tokens:", len(tokens_thematic))
print(
    "Generic thematic words removed:",
    len(tokens_base_clean) - len(tokens_thematic)
)

removed_thematic_words

Base-clean tokens: 55550
Thematic tokens: 54627
Generic thematic words removed: 923

  removed_lemma  frequency
0        relate        226
1           say        199
2       include        160
3  particularly        145
4          like        121
5        accord         72

In [26]:
# Save the thematic token dataset
tokens_thematic.to_csv(
    "../outputs/tokens_thematic.csv",
    index=False,
    encoding="utf-8-sig"
)

# Document the custom stopwords and reasons
thematic_stopword_log = pd.DataFrame({
    "stopword": [
        "accord",
        "say",
        "include",
        "like",
        "particularly",
        "relate"
    ],
    "reason": [
        "Lemma generated from the reporting phrase 'according to'",
        "Generic reporting verb",
        "Generic listing verb",
        "Generic comparison word",
        "Generic emphasis word",
        "Usually generated from the compound 'heat-related'"
    ]
})

thematic_stopword_log.to_csv(
    "../outputs/thematic_stopword_log.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Thematic tokens saved:",
      Path("../outputs/tokens_thematic.csv").exists())

print("Stopword log saved:",
      Path("../outputs/thematic_stopword_log.csv").exists())

print("Final thematic-token count:", len(tokens_thematic))

Thematic tokens saved: True
Stopword log saved: True
Final thematic-token count: 54627

In [27]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

# Reconstruct one lemmatized text per document
document_lemmas = (
    tokens_thematic
    .groupby("doc_id", sort=False)["lemma"]
    .agg(" ".join)
)

# Create two-word phrases appearing in at least 3 documents
bigram_vectorizer = CountVectorizer(
    ngram_range=(2, 2),
    min_df=3
)

bigram_matrix = bigram_vectorizer.fit_transform(
    document_lemmas
)

bigram_names = bigram_vectorizer.get_feature_names_out()

# Total occurrences across the corpus
bigram_frequency = np.asarray(
    bigram_matrix.sum(axis=0)
).ravel()

# Number of documents containing each phrase
bigram_document_frequency = np.asarray(
    (bigram_matrix > 0).sum(axis=0)
).ravel()

bigram_statistics = pd.DataFrame({
    "bigram": bigram_names,
    "frequency": bigram_frequency,
    "document_frequency": bigram_document_frequency
})

bigram_statistics["document_percentage"] = (
    bigram_statistics["document_frequency"]
    / len(document_lemmas)
    * 100
).round(1)

bigram_statistics = (
    bigram_statistics
    .sort_values(
        ["document_frequency", "frequency"],
        ascending=False
    )
    .reset_index(drop=True)
)

print("Documents:", len(document_lemmas))
print("Candidate bigrams:", len(bigram_statistics))

bigram_statistics.head(50)

Documents: 72
Candidate bigrams: 2099

                   bigram  frequency  document_frequency  document_percentage
0          climate change        407                  61                 84.7
1            extreme heat        376                  45                 62.5
2             heat stress        152                  38                 52.8
3        rise temperature        100                  32                 44.4
4            heat illness         71                  31                 43.1
5          impact climate         51                  31                 43.1
6           million child         61                  29                 40.3
7        high temperature         73                  27                 37.5
8          pregnant woman         56                  27                 37.5
9               heat wave         53                  27                 37.5
10          public health         91                  24                 33.3
11            health risk         81                  24                 33.3
12       child bangladesh         43                  24                 33.3
13        extreme weather         42                  22                 30.6
14            young child         30                  22                 30.6
15          increase risk         29                  21                 29.2
16       child vulnerable         22                  21                 29.2
17              long term         39                  20                 27.8
18          protect child         35                  20                 27.8
19       temperature rise         32                  20                 27.8
20           climate risk         27                  20                 27.8
21  vulnerable population         48                  19                 26.4
22         effect climate         29                  19                 26.4
23            heat stroke         29                  19                 26.4
24       body temperature         22                  19                 26.4
25              high risk         27                  17                 23.6
26    extreme temperature         26                  17                 23.6
27             south asia         38                  16                 22.2
28             risk index         17                  16                 22.2
29           child health        100                  15                 20.8
30          mental health         35                  15                 20.8
31       temperature soar         17                  15                 20.8
32  especially vulnerable         16                  15                 20.8
33            heat health         39                  14                 19.4
34          weather event         34                  14                 19.4
35          early warning         26                  14                 19.4
36             low income         26                  14                 19.4
37   increase temperature         25                  14                 19.4
38              sea level         25                  14                 19.4
39         degree celsius         20                  14                 19.4
40  bangladesh experience         18                  14                 19.4
41            urgent need         17                  14                 19.4
42       children climate         15                  14                 19.4
43          heat exposure        118                  13                 18.1
44         drinking water         44                  13                 18.1
45     global temperature         20                  13                 18.1
46         climate health         19                  13                 18.1
47       health condition         19                  13                 18.1
48     country bangladesh         18                  13                 18.1
49         primary school         18                  13                 18.1

In [28]:
##bigram association score

from collections import Counter
import numpy as np
import pandas as pd

# Count all individual lemmas
unigram_counts = Counter(tokens_thematic["lemma"])

# Total numbers used in the PMI calculation
total_unigrams = len(tokens_thematic)
total_bigrams = int(bigram_statistics["frequency"].sum())

# Separate the two words in each bigram
bigram_scored = bigram_statistics.copy()

bigram_scored[["word_1", "word_2"]] = (
    bigram_scored["bigram"]
    .str.split(" ", n=1, expand=True)
)

# Add individual-word frequencies
bigram_scored["word_1_frequency"] = (
    bigram_scored["word_1"].map(unigram_counts)
)

bigram_scored["word_2_frequency"] = (
    bigram_scored["word_2"].map(unigram_counts)
)

# Calculate pointwise mutual information
bigram_scored["pmi"] = np.log2(
    (
        bigram_scored["frequency"] * total_unigrams**2
    )
    /
    (
        total_bigrams
        * bigram_scored["word_1_frequency"]
        * bigram_scored["word_2_frequency"]
    )
)

# Require enough evidence to avoid emphasizing rare coincidences
bigram_review = (
    bigram_scored[
        (bigram_scored["frequency"] >= 10)
        & (bigram_scored["document_frequency"] >= 5)
    ]
    .sort_values(
        ["pmi", "document_frequency", "frequency"],
        ascending=False
    )
    .reset_index(drop=True)
)

print("Bigrams retained for review:", len(bigram_review))

bigram_review[
    [
        "bigram",
        "frequency",
        "document_frequency",
        "document_percentage",
        "pmi"
    ]
].head(50)

Bigrams retained for review: 234

,bigram,frequency,document_frequency,document_percentage,pmi
0,sheldon yett,11,11,15.3,14.070010
1,united nations,13,12,16.7,13.847618
2,densely populate,12,7,9.7,13.147178
3,data collection,11,5,6.9,12.914732
4,tell afp,12,6,8.3,12.839056
5,index ccri,11,10,13.9,12.654973
6,directorate general,10,9,12.5,12.391939
7,greenhouse gas,15,9,12.5,12.369571
8,bear brunt,11,11,15.3,12.171890
9,meteorological department,15,11,15.3,12.160984
10,fossil fuel,13,7,9.7,12.070010
11,degree celsius,20,14,19.4,11.751694
12,informal settlement,15,6,8.3,11.748082
13,newborn infant,11,11,15.3,11.737194
14,degree fahrenheit,11,9,12.5,11.581075
15,preterm birth,16,8,11.1,11.578157
16,stay hydrated,14,8,11.1,11.513961
17,order closure,10,10,13.9,11.437742
18,urge parent,10,10,13.9,11.430007
19,air conditioning,15,10,13.9,11.315123
20,food security,18,8,11.1,11.136648
21,human induced,10,7,9.7,11.100384
22,south asia,38,16,22.2,11.099173
23,world bank,17,10,13.9,10.900085
24,infant young,14,13,18.1,10.873613
25,frequency intensity,15,8,11.1,10.850197
26,air pollution,17,9,12.5,10.817623
27,safe drinking,20,10,13.9,10.777229
28,underscore urgent,10,10,13.9,10.762582
29,past decade,10,8,11.1,10.654973
30,sea level,25,14,19.4,10.537278
31,cognitive development,11,7,9.7,10.436685
32,cop strategy,10,6,8.3,10.414659
33,pregnant woman,56,27,37.5,10.410100
34,frequent intense,13,10,13.9,10.408506
35,early warning,26,14,19.4,10.212029
36,long term,39,20,27.8,10.124592
37,primary mass,10,10,13.9,10.115814
38,air quality,10,5,6.9,10.113489
39,unicef urge,14,8,11.1,10.014212
40,local authority,11,10,13.9,9.985122
41,social protection,10,7,9.7,9.803224
42,primary secondary,10,8,11.1,9.737303
43,dehydration heatstroke,10,9,12.5,9.719513
44,global warming,27,11,15.3,9.584107
45,early life,40,5,6.9,9.432420
46,urgent need,17,14,19.4,9.388186
47,mass education,10,10,13.9,9.388186
48,outdoor worker,10,6,8.3,9.387718
49,negatively affect,10,6,8.3,9.294345

In [29]:
import re
import pandas as pd

phrases_to_inspect = [
    "sheldon yett",
    "tell afp",
    "index ccri",
    "unicef urge",
    "primary mass",
    "mass education"
]

phrase_document_rows = []

for phrase in phrases_to_inspect:
    phrase_pattern = rf"\b{re.escape(phrase)}\b"

    matching_documents = document_lemmas[
        document_lemmas.str.contains(
            phrase_pattern,
            regex=True,
            na=False
        )
    ].index

    for doc_id in matching_documents:
        phrase_document_rows.append({
            "phrase": phrase,
            "doc_id": doc_id
        })

phrase_document_review = pd.DataFrame(
    phrase_document_rows
)

# Include whichever metadata columns are available
metadata_candidates = [
    "doc_id",
    "title",
    "source_type",
    "publication_date",
    "year",
    "domain",
    "url"
]

metadata_columns = [
    column
    for column in metadata_candidates
    if column in corpus_analysis.columns
]

phrase_document_review = (
    phrase_document_review
    .merge(
        corpus_analysis[metadata_columns].drop_duplicates(
            subset="doc_id"
        ),
        on="doc_id",
        how="left"
    )
    .sort_values(["phrase", "doc_id"])
    .reset_index(drop=True)
)

phrase_document_review

,phrase,doc_id,source_type,url
0,index ccri,DOC_002,civil society,https://www.unicef.org/bangladesh/en/press-rel...
1,index ccri,DOC_008,news paper,https://www.thedailystar.net/news/bangladesh/n...
2,index ccri,DOC_011,news paper,https://en.prothomalo.com/bangladesh/wftdj08h8e
3,index ccri,DOC_012,news paper,https://www.pressenza.com/2025/07/children-at-...
4,index ccri,DOC_034,news paper,https://english.news.cn/20240424/55dd98f670c54...
5,index ccri,DOC_037,news paper,https://www.risingbd.com/english/national/news...
6,index ccri,DOC_042,news paper,https://voice7news.tv/public/bangladesh/news/3834
7,index ccri,DOC_052,news paper,https://viewsbangladesh.com/children-of-bangla...
8,index ccri,DOC_054,news paper,https://www.thedailystar.net/star-health/news/...
9,index ccri,DOC_083,civil society,https://www.unicef.org/press-releases/soaring-...
10,mass education,DOC_002,civil society,https://www.unicef.org/bangladesh/en/press-rel...
11,mass education,DOC_008,news paper,https://www.thedailystar.net/news/bangladesh/n...
12,mass education,DOC_011,news paper,https://en.prothomalo.com/bangladesh/wftdj08h8e
13,mass education,DOC_012,news paper,https://www.pressenza.com/2025/07/children-at-...
14,mass education,DOC_016,news paper,https://www.newagebd.net/print/post/233451
15,mass education,DOC_029,news paper,https://www.independent.co.uk/asia/south-asia/...
16,mass education,DOC_034,news paper,https://english.news.cn/20240424/55dd98f670c54...
17,mass education,DOC_037,news paper,https://www.risingbd.com/english/national/news...
18,mass education,DOC_042,news paper,https://voice7news.tv/public/bangladesh/news/3834
19,mass education,DOC_052,news paper,https://viewsbangladesh.com/children-of-bangla...
20,primary mass,DOC_002,civil society,https://www.unicef.org/bangladesh/en/press-rel...
21,primary mass,DOC_008,news paper,https://www.thedailystar.net/news/bangladesh/n...
22,primary mass,DOC_011,news paper,https://en.prothomalo.com/bangladesh/wftdj08h8e
23,primary mass,DOC_012,news paper,https://www.pressenza.com/2025/07/children-at-...
24,primary mass,DOC_016,news paper,https://www.newagebd.net/print/post/233451
25,primary mass,DOC_029,news paper,https://www.independent.co.uk/asia/south-asia/...
26,primary mass,DOC_034,news paper,https://english.news.cn/20240424/55dd98f670c54...
27,primary mass,DOC_037,news paper,https://www.risingbd.com/english/national/news...
28,primary mass,DOC_042,news paper,https://voice7news.tv/public/bangladesh/news/3834
29,primary mass,DOC_052,news paper,https://viewsbangladesh.com/children-of-bangla...
30,sheldon yett,DOC_007,civil society,https://www.preventionweb.net/news/new-guideli...
31,sheldon yett,DOC_008,news paper,https://www.thedailystar.net/news/bangladesh/n...
32,sheldon yett,DOC_011,news paper,https://en.prothomalo.com/bangladesh/wftdj08h8e
33,sheldon yett,DOC_016,news paper,https://www.newagebd.net/print/post/233451
34,sheldon yett,DOC_034,news paper,https://english.news.cn/20240424/55dd98f670c54...
35,sheldon yett,DOC_037,news paper,https://www.risingbd.com/english/national/news...
36,sheldon yett,DOC_042,news paper,https://voice7news.tv/public/bangladesh/news/3834
37,sheldon yett,DOC_043,civil society,https://bangladesh.un.org/en/267869-unicef-sup...
38,sheldon yett,DOC_044,news paper,https://www.dhakatribune.com/bangladesh/health...
39,sheldon yett,DOC_052,news paper,https://viewsbangladesh.com/children-of-bangla...
40,sheldon yett,DOC_068,news paper,https://reliefweb.int/report/bangladesh/new-gu...
41,tell afp,DOC_024,news paper,https://www.bbc.com/news/articles/c1wxjj3g965o
42,tell afp,DOC_029,news paper,https://www.independent.co.uk/asia/south-asia/...
43,tell afp,DOC_030,news paper,https://english.aawsat.com/varieties/4986126-b...
44,tell afp,DOC_039,news paper,https://english.alarabiya.net/News/world/2024/...
45,tell afp,DOC_040,news paper,https://www.france24.com/en/live-news/20240429...
46,tell afp,DOC_047,news paper,https://www.aljazeera.com/news/2024/4/28/bangl...
47,unicef urge,DOC_002,civil society,https://www.unicef.org/bangladesh/en/press-rel...
48,unicef urge,DOC_008,news paper,https://www.thedailystar.net/news/bangladesh/n...
49,unicef urge,DOC_011,news paper,https://en.prothomalo.com/bangladesh/wftdj08h8e
50,unicef urge,DOC_016,news paper,https://www.newagebd.net/print/post/233451
51,unicef urge,DOC_034,news paper,https://english.news.cn/20240424/55dd98f670c54...
52,unicef urge,DOC_037,news paper,https://www.risingbd.com/english/national/news...
53,unicef urge,DOC_052,news paper,https://viewsbangladesh.com/children-of-bangla...
54,unicef urge,DOC_083,civil society,https://www.unicef.org/press-releases/soaring-...

In [30]:
import numpy as np
import pandas as pd

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Keep document order stable
similarity_documents = document_lemmas.sort_index()
document_ids = similarity_documents.index.to_list()

# Use sequences of 3–5 words to detect shared wording
overlap_vectorizer = TfidfVectorizer(
    ngram_range=(3, 5),
    min_df=1,
    sublinear_tf=True
)

overlap_matrix = overlap_vectorizer.fit_transform(
    similarity_documents
)

similarity_matrix = cosine_similarity(overlap_matrix)

# Convert the upper triangle into document pairs
similarity_rows = []

for first_index in range(len(document_ids)):
    for second_index in range(
        first_index + 1,
        len(document_ids)
    ):
        similarity_rows.append({
            "doc_id_1": document_ids[first_index],
            "doc_id_2": document_ids[second_index],
            "cosine_similarity": similarity_matrix[
                first_index,
                second_index
            ]
        })

document_similarity_pairs = (
    pd.DataFrame(similarity_rows)
    .sort_values(
        "cosine_similarity",
        ascending=False
    )
    .reset_index(drop=True)
)

# Add available document metadata
metadata_candidates = [
    "doc_id",
    "title",
    "source_type",
    "url"
]

metadata_columns = [
    column
    for column in metadata_candidates
    if column in corpus_analysis.columns
]

document_metadata = (
    corpus_analysis[metadata_columns]
    .drop_duplicates(subset="doc_id")
)

document_similarity_review = (
    document_similarity_pairs
    .merge(
        document_metadata.add_suffix("_1"),
        on="doc_id_1",
        how="left"
    )
    .merge(
        document_metadata.add_suffix("_2"),
        on="doc_id_2",
        how="left"
    )
)

document_similarity_review[
    [
        column
        for column in [
            "doc_id_1",
            "doc_id_2",
            "cosine_similarity",
            "title_1",
            "title_2",
            "source_type_1",
            "source_type_2"
        ]
        if column in document_similarity_review.columns
    ]
].head(30)

   doc_id_1 doc_id_2  cosine_similarity  source_type_1  source_type_2
0   DOC_007  DOC_068           0.985480  civil society     news paper
1   DOC_043  DOC_068           0.948256  civil society     news paper
2   DOC_007  DOC_043           0.934372  civil society  civil society
3   DOC_019  DOC_023           0.902858  civil society     news paper
4   DOC_002  DOC_052           0.857464  civil society     news paper
5   DOC_013  DOC_025           0.854975  civil society     news paper
6   DOC_002  DOC_011           0.800920  civil society     news paper
7   DOC_011  DOC_052           0.789797     news paper     news paper
8   DOC_008  DOC_011           0.728154     news paper     news paper
9   DOC_002  DOC_008           0.712332  civil society     news paper
10  DOC_008  DOC_052           0.650415     news paper     news paper
11  DOC_011  DOC_034           0.475774     news paper     news paper
12  DOC_034  DOC_052           0.458594     news paper     news paper
13  DOC_002  DOC_034           0.429260  civil society     news paper
14  DOC_015  DOC_025           0.417929     news paper     news paper
15  DOC_013  DOC_015           0.409938  civil society     news paper
16  DOC_016  DOC_034           0.372968     news paper     news paper
17  DOC_002  DOC_016           0.328621  civil society     news paper
18  DOC_011  DOC_016           0.316509     news paper     news paper
19  DOC_016  DOC_052           0.304770     news paper     news paper
20  DOC_043  DOC_044           0.294280  civil society     news paper
21  DOC_044  DOC_068           0.292354     news paper     news paper
22  DOC_008  DOC_034           0.289862     news paper     news paper
23  DOC_007  DOC_044           0.282910  civil society     news paper
24  DOC_008  DOC_016           0.280273     news paper     news paper
25  DOC_001  DOC_038           0.224473     news paper     news paper
26  DOC_002  DOC_037           0.223242  civil society     news paper
27  DOC_001  DOC_004           0.214843     news paper     news paper
28  DOC_011  DOC_037           0.214226     news paper     news paper
29  DOC_064  DOC_079           0.209061     scientific     scientific

In [31]:
# Provisional threshold for manual near-duplicate review
similarity_threshold = 0.70

near_duplicate_pairs = (
    document_similarity_pairs[
        document_similarity_pairs["cosine_similarity"]
        >= similarity_threshold
    ]
    .copy()
    .reset_index(drop=True)
)

# Union–find functions for grouping connected document pairs
parent = {
    doc_id: doc_id
    for doc_id in document_ids
}

def find_root(doc_id):
    while parent[doc_id] != doc_id:
        parent[doc_id] = parent[parent[doc_id]]
        doc_id = parent[doc_id]
    return doc_id

def join_documents(doc_id_1, doc_id_2):
    root_1 = find_root(doc_id_1)
    root_2 = find_root(doc_id_2)

    if root_1 != root_2:
        parent[root_2] = root_1

# Join documents connected by high similarity
for _, row in near_duplicate_pairs.iterrows():
    join_documents(
        row["doc_id_1"],
        row["doc_id_2"]
    )

# Collect connected groups
connected_groups = {}

for doc_id in document_ids:
    root = find_root(doc_id)

    connected_groups.setdefault(
        root,
        []
    ).append(doc_id)

# Retain only groups containing multiple documents
duplicate_groups = [
    sorted(group)
    for group in connected_groups.values()
    if len(group) > 1
]

duplicate_groups = sorted(
    duplicate_groups,
    key=lambda group: group[0]
)

# Create a document-level review table
cluster_rows = []

for cluster_number, group in enumerate(
    duplicate_groups,
    start=1
):
    cluster_id = f"ND_{cluster_number:02d}"

    for doc_id in group:
        cluster_rows.append({
            "doc_id": doc_id,
            "near_duplicate_cluster": cluster_id,
            "thematic_token_count": len(
                document_lemmas.loc[doc_id].split()
            )
        })

near_duplicate_clusters = pd.DataFrame(
    cluster_rows
)

# Add available metadata
near_duplicate_cluster_review = (
    near_duplicate_clusters
    .merge(
        document_metadata,
        on="doc_id",
        how="left"
    )
    .sort_values(
        ["near_duplicate_cluster", "doc_id"]
    )
    .reset_index(drop=True)
)

near_duplicate_cluster_review

,doc_id,near_duplicate_cluster,thematic_token_count,source_type,url
0,DOC_002,ND_01,217,civil society,https://www.unicef.org/bangladesh/en/press-rel...
1,DOC_008,ND_01,222,news paper,https://www.thedailystar.net/news/bangladesh/n...
2,DOC_011,ND_01,227,news paper,https://en.prothomalo.com/bangladesh/wftdj08h8e
3,DOC_052,ND_01,224,news paper,https://viewsbangladesh.com/children-of-bangla...
4,DOC_007,ND_02,350,civil society,https://www.preventionweb.net/news/new-guideli...
5,DOC_043,ND_02,372,civil society,https://bangladesh.un.org/en/267869-unicef-sup...
6,DOC_068,ND_02,350,news paper,https://reliefweb.int/report/bangladesh/new-gu...
7,DOC_013,ND_03,342,civil society,https://www.unicef.org/bangladesh/en/press-rel...
8,DOC_025,ND_03,332,news paper,https://bdnews24.com/bangladesh/7387478f9b08
9,DOC_019,ND_04,349,civil society,https://www.savethechildren.org/us/about-us/me...
10,DOC_023,ND_04,347,news paper,https://reliefweb.int/report/bangladesh/bangla...

In [32]:
# Select one representative from each confirmed cluster
cluster_representatives = {
    "ND_01": "DOC_002",
    "ND_02": "DOC_043",
    "ND_03": "DOC_013",
    "ND_04": "DOC_019"
}

# Record the representative selected for each cluster
near_duplicate_decisions = (
    near_duplicate_cluster_review
    .copy()
)

near_duplicate_decisions["representative_doc_id"] = (
    near_duplicate_decisions[
        "near_duplicate_cluster"
    ].map(cluster_representatives)
)

near_duplicate_decisions[
    "retain_for_unique_content_analysis"
] = (
    near_duplicate_decisions["doc_id"]
    == near_duplicate_decisions["representative_doc_id"]
)

near_duplicate_decisions["decision_reason"] = np.where(
    near_duplicate_decisions[
        "retain_for_unique_content_analysis"
    ],
    "Retained as cluster representative",
    "Retained in master corpus but omitted from unique-content analysis"
)

# Identify the seven non-representative documents
near_duplicate_omissions = set(
    near_duplicate_decisions.loc[
        ~near_duplicate_decisions[
            "retain_for_unique_content_analysis"
        ],
        "doc_id"
    ]
)

print(
    "Documents omitted from unique-content analysis:",
    sorted(near_duplicate_omissions)
)

# Add duplicate information to the 72-document corpus
cluster_information = (
    near_duplicate_decisions[
        [
            "doc_id",
            "near_duplicate_cluster",
            "representative_doc_id"
        ]
    ]
    .drop_duplicates(subset="doc_id")
)

corpus_analysis_flagged = (
    corpus_analysis
    .merge(
        cluster_information,
        on="doc_id",
        how="left"
    )
)

corpus_analysis_flagged[
    "retain_for_unique_content_analysis"
] = (
    ~corpus_analysis_flagged["doc_id"].isin(
        near_duplicate_omissions
    )
)

# Create the deduplicated analytical corpus
corpus_analysis_unique = (
    corpus_analysis_flagged[
        corpus_analysis_flagged[
            "retain_for_unique_content_analysis"
        ]
    ]
    .copy()
    .reset_index(drop=True)
)

# Create corresponding thematic-token dataset
tokens_thematic_unique = (
    tokens_thematic[
        tokens_thematic["doc_id"].isin(
            corpus_analysis_unique["doc_id"]
        )
    ]
    .copy()
    .reset_index(drop=True)
)

# Reconstruct document texts from the unique-content tokens
document_lemmas_unique = (
    tokens_thematic_unique
    .groupby("doc_id", sort=False)["lemma"]
    .agg(" ".join)
)

print("\nMaster analytical corpus:", len(corpus_analysis_flagged))
print("Unique-content corpus:", len(corpus_analysis_unique))
print("Documents omitted as near-duplicates:",
      len(near_duplicate_omissions))

print("\nUnique-content source distribution:")
print(
    corpus_analysis_unique["source_type"]
    .value_counts()
)

# Save the audit files
near_duplicate_decisions.to_csv(
    "../outputs/near_duplicate_decisions.csv",
    index=False,
    encoding="utf-8-sig"
)

corpus_analysis_flagged.to_csv(
    "../outputs/corpus_analysis_flagged.csv",
    index=False,
    encoding="utf-8-sig"
)

corpus_analysis_unique.to_csv(
    "../outputs/corpus_analysis_unique.csv",
    index=False,
    encoding="utf-8-sig"
)

tokens_thematic_unique.to_csv(
    "../outputs/tokens_thematic_unique.csv",
    index=False,
    encoding="utf-8-sig"
)

Documents omitted from unique-content analysis: ['DOC_007', 'DOC_008', 'DOC_011', 'DOC_023', 'DOC_025', 'DOC_052', 'DOC_068']

Master analytical corpus: 72
Unique-content corpus: 65
Documents omitted as near-duplicates: 7

Unique-content source distribution:
source_type
news paper       40
civil society    15
scientific        9
others            1
Name: count, dtype: int64

In [33]:
# Inspect the document classified as "others"
metadata_candidates = [
    "doc_id",
    "title",
    "source_type",
    "publisher",
    "domain",
    "url"
]

available_metadata = [
    column
    for column in metadata_candidates
    if column in corpus_analysis_unique.columns
]

other_source_review = corpus_analysis_unique.loc[
    corpus_analysis_unique["source_type"]
    .str.strip()
    .str.lower()
    .eq("others"),
    available_metadata
]

other_source_review.T

                                                            42
doc_id                                                 DOC_057
source_type                                             others
url          https://nationalhospital.com.bd/extreme-heat-i...

In [34]:
from collections import Counter

import numpy as np
import pandas as pd

from sklearn.feature_extraction.text import CountVectorizer

# --------------------------------------------------
# 1. Divide the unique-content corpus
# --------------------------------------------------

public_source_types = {
    "news paper",
    "civil society",
    "others"
}

normalized_source_type = (
    corpus_analysis_unique["source_type"]
    .str.strip()
    .str.lower()
)

public_corpus = (
    corpus_analysis_unique[
        normalized_source_type.isin(public_source_types)
    ]
    .copy()
    .reset_index(drop=True)
)

scientific_corpus = (
    corpus_analysis_unique[
        normalized_source_type.eq("scientific")
    ]
    .copy()
    .reset_index(drop=True)
)

# --------------------------------------------------
# 2. Create corresponding token datasets
# --------------------------------------------------

public_document_ids = set(public_corpus["doc_id"])
scientific_document_ids = set(scientific_corpus["doc_id"])

tokens_thematic_public = (
    tokens_thematic_unique[
        tokens_thematic_unique["doc_id"].isin(
            public_document_ids
        )
    ]
    .copy()
    .reset_index(drop=True)
)

tokens_thematic_scientific = (
    tokens_thematic_unique[
        tokens_thematic_unique["doc_id"].isin(
            scientific_document_ids
        )
    ]
    .copy()
    .reset_index(drop=True)
)

# Reconstruct one processed text per public document
document_lemmas_public = (
    tokens_thematic_public
    .groupby("doc_id", sort=False)["lemma"]
    .agg(" ".join)
)

# --------------------------------------------------
# 3. Calculate public-corpus unigram statistics
# --------------------------------------------------

number_of_public_documents = len(public_corpus)

public_unigram_statistics = (
    tokens_thematic_public
    .groupby("lemma")
    .agg(
        frequency=("lemma", "size"),
        document_frequency=("doc_id", "nunique")
    )
    .reset_index()
)

public_unigram_statistics["document_percentage"] = (
    public_unigram_statistics["document_frequency"]
    / number_of_public_documents
    * 100
).round(1)

public_unigram_statistics = (
    public_unigram_statistics
    .sort_values(
        ["document_frequency", "frequency"],
        ascending=False
    )
    .reset_index(drop=True)
)

# --------------------------------------------------
# 4. Calculate public-corpus bigram statistics
# --------------------------------------------------

public_bigram_vectorizer = CountVectorizer(
    ngram_range=(2, 2),
    min_df=3
)

public_bigram_matrix = (
    public_bigram_vectorizer
    .fit_transform(document_lemmas_public)
)

public_bigram_names = (
    public_bigram_vectorizer
    .get_feature_names_out()
)

public_bigram_frequency = np.asarray(
    public_bigram_matrix.sum(axis=0)
).ravel()

public_bigram_document_frequency = np.asarray(
    (public_bigram_matrix > 0).sum(axis=0)
).ravel()

public_bigram_statistics = pd.DataFrame({
    "bigram": public_bigram_names,
    "frequency": public_bigram_frequency,
    "document_frequency":
        public_bigram_document_frequency
})

public_bigram_statistics["document_percentage"] = (
    public_bigram_statistics["document_frequency"]
    / number_of_public_documents
    * 100
).round(1)

# --------------------------------------------------
# 5. Calculate corrected PMI scores
# --------------------------------------------------

public_unigram_counts = Counter(
    tokens_thematic_public["lemma"]
)

total_public_unigrams = len(tokens_thematic_public)

# All possible bigram positions, including rare bigrams
total_public_bigram_positions = sum(
    max(len(text.split()) - 1, 0)
    for text in document_lemmas_public
)

public_bigram_statistics[
    ["word_1", "word_2"]
] = (
    public_bigram_statistics["bigram"]
    .str.split(" ", n=1, expand=True)
)

public_bigram_statistics["word_1_frequency"] = (
    public_bigram_statistics["word_1"]
    .map(public_unigram_counts)
)

public_bigram_statistics["word_2_frequency"] = (
    public_bigram_statistics["word_2"]
    .map(public_unigram_counts)
)

public_bigram_statistics["pmi"] = np.log2(
    (
        public_bigram_statistics["frequency"]
        / total_public_bigram_positions
    )
    /
    (
        (
            public_bigram_statistics["word_1_frequency"]
            / total_public_unigrams
        )
        *
        (
            public_bigram_statistics["word_2_frequency"]
            / total_public_unigrams
        )
    )
)

public_bigram_statistics = (
    public_bigram_statistics
    .sort_values(
        ["document_frequency", "frequency"],
        ascending=False
    )
    .reset_index(drop=True)
)

public_bigram_review = (
    public_bigram_statistics[
        (public_bigram_statistics["frequency"] >= 10)
        & (
            public_bigram_statistics[
                "document_frequency"
            ] >= 5
        )
    ]
    .sort_values(
        ["pmi", "document_frequency", "frequency"],
        ascending=False
    )
    .reset_index(drop=True)
)

# --------------------------------------------------
# 6. Validate and save everything
# --------------------------------------------------

print("Public-facing documents:", len(public_corpus))
print("Scientific documents:", len(scientific_corpus))

print("\nPublic source distribution:")
print(public_corpus["source_type"].value_counts())

print("\nPublic thematic tokens:",
      len(tokens_thematic_public))

print("Candidate public bigrams:",
      len(public_bigram_statistics))

print("Public bigrams retained for review:",
      len(public_bigram_review))

public_corpus.to_csv(
    "../outputs/public_corpus_unique.csv",
    index=False,
    encoding="utf-8-sig"
)

scientific_corpus.to_csv(
    "../outputs/scientific_corpus_unique.csv",
    index=False,
    encoding="utf-8-sig"
)

tokens_thematic_public.to_csv(
    "../outputs/tokens_thematic_public.csv",
    index=False,
    encoding="utf-8-sig"
)

public_unigram_statistics.to_csv(
    "../outputs/public_unigram_statistics.csv",
    index=False,
    encoding="utf-8-sig"
)

public_bigram_statistics.to_csv(
    "../outputs/public_bigram_statistics.csv",
    index=False,
    encoding="utf-8-sig"
)

public_bigram_review.to_csv(
    "../outputs/public_bigram_review.csv",
    index=False,
    encoding="utf-8-sig"
)

display(public_unigram_statistics.head(30))

display(
    public_bigram_statistics[
        [
            "bigram",
            "frequency",
            "document_frequency",
            "document_percentage",
            "pmi"
        ]
    ].head(30)
)

Public-facing documents: 56
Scientific documents: 9

Public source distribution:
source_type
news paper       40
civil society    15
others            1
Name: count, dtype: int64

Public thematic tokens: 21579
Candidate public bigrams: 831
Public bigrams retained for review: 67

          lemma  frequency  document_frequency  document_percentage
0          heat        592                  54                 96.4
1    bangladesh        312                  53                 94.6
2   temperature        266                  53                 94.6
3       climate        313                  52                 92.9
4         child        423                  51                 91.1
5        health        282                  48                 85.7
6       country        139                  48                 85.7
7        change        160                  47                 83.9
8          high        121                  47                 83.9
9      heatwave        223                  46                 82.1
10      extreme        191                  46                 82.1
11          day        124                  44                 78.6
12   vulnerable         94                  44                 78.6
13         risk        157                  43                 76.8
14       impact        111                  42                 75.0
15         rise        122                  40                 71.4
16     increase        104                  39                 69.6
17       school        133                  37                 66.1
18         year        128                  36                 64.3
19        water        117                  36                 64.3
20      million        107                  35                 62.5
21   government         56                  35                 62.5
22       people        108                  34                 60.7
23    condition         74                  33                 58.9
24         face         62                  33                 58.9
25          hot         68                  32                 57.1
26         need         65                  32                 57.1
27      weather         61                  32                 57.1
28      illness         59                  32                 57.1
29   experience         61                  31                 55.4

,bigram,frequency,document_frequency,document_percentage,pmi
0,climate change,144,45,80.4,5.959067
1,extreme heat,126,37,66.1,4.591487
2,heat stress,68,26,46.4,4.869708
3,rise temperature,42,24,42.9,4.807387
4,million child,47,23,41.1,4.489697
5,heat illness,31,22,39.3,4.263189
6,heat wave,37,19,33.9,5.153162
7,public health,30,19,33.9,5.553719
8,high temperature,29,19,33.9,4.284925
9,pregnant woman,36,18,32.1,7.981831
10,impact climate,26,18,32.1,4.017094
11,health risk,27,16,28.6,3.721805
12,young child,22,16,28.6,5.091613
13,temperature rise,18,15,26.8,3.584994
14,child vulnerable,15,15,26.8,3.028877
15,protect child,24,14,25.0,4.354647
16,child bangladesh,23,14,25.0,1.914735
17,heat stroke,23,14,25.0,5.130235
18,body temperature,17,14,25.0,4.705349
19,increase risk,14,14,25.0,4.213384
20,extreme weather,25,13,23.2,5.536779
21,degree celsius,19,13,23.2,9.079161
22,severe heatwave,16,12,21.4,4.927764
23,early warning,15,12,21.4,8.356695
24,climate risk,14,12,21.4,2.623805
25,long term,14,12,21.4,8.646202
26,temperature soar,14,12,21.4,5.568199
27,extreme temperature,13,12,21.4,2.468818
28,capital dhaka,12,12,21.4,7.115687
29,south asia,26,11,19.6,8.183411